MvcCoreLinqToXML/Models/Cliente.cs
namespace MvcCoreLinqToXML.Models
{
    public class Cliente
    {
        public int IdCliente { get; set; }

        public string Nombre { get; set; }

        public string Direccion { get; set; }

        public string Email { get; set; }

        public string ImagenCliente { get; set; }
    }
}

MvcCoreLinqToXML/Models/ErrorViewModel.cs
namespace MvcCoreLinqToXML.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCoreLinqToXML/Models/Escena.cs
namespace MvcCoreLinqToXML.Models
{
    public class Escena
    {
        public int IdPelicula { get; set; }

        public string Titulo { get; set; }

        public string Descripcion { get; set; }

        public string Imagen { get; set; }
    }
}

MvcCoreLinqToXML/Models/Joyeria.cs
namespace MvcCoreLinqToXML.Models
{
    public class Joyeria
    {
        public string Nombre { get; set; }

        public string Telefono { get; set; }

        public string CIF { get; set; }

        public string Direccion { get; set; }
    }
}

MvcCoreLinqToXML/Models/Pelicula.cs
namespace MvcCoreLinqToXML.Models
{
    public class Pelicula
    {
        public int IdPelicula { get; set; }

        public string Titulo { get; set; }

        public string TituloOriginal { get; set; }

        public string Descripcion { get; set; }

        public string Poster { get; set; }
    }
}

MvcCoreLinqToXML/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToXML.Models;
using MvcCoreLinqToXML.Repositories;

namespace MvcCoreLinqToXML.Controllers
{

    public class ClientesController : Controller
    {
        private RepositoryXML repo;

        public ClientesController(RepositoryXML repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Cliente> clientes = this.repo.GetClientes();
            return View(clientes);
        }

        public IActionResult Details(int idcliente)
        {
            Cliente cliente = this.repo.FindCliente(idcliente);
            return View(cliente);
        }

        public IActionResult Delete(int idcliente)
        {
            this.repo.DeleteCliente(idcliente);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int idcliente)
        {
            Cliente cliente = this.repo.FindCliente(idcliente);
            return View(cliente);
        }
        [HttpPost]
        public IActionResult Update(Cliente cliente)
        {
            this.repo.UpdateCliente(cliente.IdCliente
                , cliente.Nombre, cliente.Direccion, cliente.Email
                , cliente.ImagenCliente);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Cliente cliente)
        {
            this.repo.CreateCliente(cliente.IdCliente
                , cliente.Nombre, cliente.Direccion
                , cliente.Email, cliente.ImagenCliente);
            return RedirectToAction("Index");
        }
    }
}

MvcCoreLinqToXML/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToXML.Models;
using System.Diagnostics;

namespace MvcCoreLinqToXML.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCoreLinqToXML/Controllers/JoyeriasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToXML.Models;
using MvcCoreLinqToXML.Repositories;

namespace MvcCoreLinqToXML.Controllers
{
    public class JoyeriasController : Controller
    {
        private RepositoryXML repo;

        public JoyeriasController(RepositoryXML repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Joyeria> joyerias = this.repo.GetJoyerias();
            return View(joyerias);
        }
    }
}

MvcCoreLinqToXML/Controllers/PeliculasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreLinqToXML.Models;
using MvcCoreLinqToXML.Repositories;

namespace MvcCoreLinqToXML.Controllers
{
    public class PeliculasController : Controller
    {
        private RepositoryPeliculas repo;

        public PeliculasController(RepositoryPeliculas repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Pelicula> pelis = this.repo.GetPeliculas();
            return View(pelis);
        }

        public IActionResult EscenasPelicula(int idpelicula)
        {
            Pelicula peli = this.repo.FindPelicula(idpelicula);
            ViewData["PELICULA"] = peli;
            List<Escena> escenas = this.repo.GetEscenasPelicula(idpelicula);
            return View(escenas);
        }

        public IActionResult DetallePeliculaEscena(int idpelicula, int? posicion)
        {
            //LINQ FUNCIONA EN BASE 0
            //SQL SERVER FUNCIONA EN BASE 1
            if(posicion == null)
            {
                posicion = 0;
            }
            int numeroEscenas = 0;
            Escena escena = this.repo.GetEscenaPelicula
                (idpelicula, posicion.Value, ref numeroEscenas);
            ViewData["DATO"] = "Escena " + (posicion + 1)
                + " de " + numeroEscenas;
            int siguiente = posicion.Value + 1;
            if(siguiente >= numeroEscenas)
            {
                siguiente = 0;
            }
            int anterior = posicion.Value - 1;
            if(anterior < 0)
            {
                anterior = numeroEscenas - 1;
            }
            ViewData["SIGUIENTE"] = siguiente;
            ViewData["ANTERIOR"] = anterior;
            Pelicula peli = this.repo.FindPelicula(idpelicula);
            ViewData["PELICULA"] = peli;
            return View(escena);
        }
    }
}

MvcCoreLinqToXML/Views/Clientes/Create.cshtml
@model MvcCoreLinqToXML.Models.Cliente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagenCliente" class="control-label"></label>
                <input asp-for="ImagenCliente" class="form-control" />
                <span asp-validation-for="ImagenCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCoreLinqToXML/Views/Clientes/Details.cshtml
@model Cliente

<a asp-controller="Clientes" asp-action="Index">
    Volver a Index
</a>

<div>
    <img src="@Model.ImagenCliente" class="card-img-top" style="width:200px"/>
    <h4>@Model.Nombre</h4>
    <h5>@Model.Direccion</h5>
    <a asp-controller="Clientes" asp-action="Delete" asp-route-idcliente="@Model.IdCliente">Eliminar</a>
</div>

MvcCoreLinqToXML/Views/Clientes/Index.cshtml
@model IEnumerable<MvcCoreLinqToXML.Models.Cliente>

@{
    ViewData["Title"] = "Clientes";
}

<h1>Clientes</h1>

<p>
    <a asp-controller="Clientes" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagenCliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagenCliente)
            </td>
            <td>
                <a asp-controller="Clientes" asp-action="Details" asp-route-idcliente="@item.IdCliente">Detalles</a>
                <a asp-controller="Clientes" asp-action="Update" asp-route-idcliente="@item.IdCliente">Editar</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreLinqToXML/Views/Clientes/Update.cshtml
@model MvcCoreLinqToXML.Models.Cliente

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="idcliente" value="@Model.IdCliente"/>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagenCliente" class="control-label"></label>
                <input asp-for="ImagenCliente" class="form-control" />
                <span asp-validation-for="ImagenCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcCoreLinqToXML/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCoreLinqToXML/Views/Joyerias/Index.cshtml
@model IEnumerable<MvcCoreLinqToXML.Models.Joyeria>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CIF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CIF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreLinqToXML/Views/Peliculas/DetallePeliculaEscena.cshtml
@model Escena
 
@{
    Pelicula peli = ViewData["PELICULA"] as Pelicula;
}
 
@{
    ViewData["Title"] = "EscenasPelicula";
}
 
<h1>Detalles Pelicula</h1>
 
<div class="card" style="width: 28rem; float:left">
    <img class="card-img-top" src="@peli.Poster" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@peli.Titulo</h5>
        <p class="card-text">Título original: @peli.TituloOriginal</p>
        <p class="card-text">@peli.Descripcion</p>
        <a asp-controller="Peliculas" asp-action="Index"
           class="btn btn-primary">Volver</a>
    </div>
</div>
 
<div class="card" style="width: 28rem; float:left">
    <h4 style="color:blue">@ViewData["DATOS"]</h4>
    <a asp-controller="Peliculas" asp-action="DetallePeliculaEscena"
       asp-route-posicion="@ViewData["ANTERIOR"]"
       asp-route-idpelicula="@Model.IdPelicula"
       class="btn btn-danger">Anterior</a>
    <a asp-controller="Peliculas" asp-action="DetallePeliculaEscena"
        asp-route-idpelicula="@Model.IdPelicula"
       asp-route-posicion="@ViewData["SIGUIENTE"]"
       class="btn btn-default">Siguiente</a>
    <img class="card-img-top" src="@Model.Imagen" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Titulo</h5>
        <p class="card-text">@Model.Descripcion</p>
 
    </div>
</div>

MvcCoreLinqToXML/Views/Peliculas/EscenasPelicula.cshtml
@model IEnumerable<MvcCoreLinqToXML.Models.Escena>

@{
    ViewData["Title"] = "EscenasPelicula";
}

<h1>EscenasPelicula</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPelicula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPelicula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreLinqToXML/Views/Peliculas/Index.cshtml
@model IEnumerable<MvcCoreLinqToXML.Models.Pelicula>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPelicula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TituloOriginal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poster)
            </th>
            <th>
                Escenas Pelicula
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPelicula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TituloOriginal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Poster)
            </td>
            <td>
                <a asp-controller="Peliculas" asp-action="EscenasPelicula" asp-route-idpelicula="@item.IdPelicula">Escena Pelicula</a>
                <a asp-controller="Peliculas" asp-action="DetallePeliculaEscena" asp-route-idpelicula="@item.IdPelicula">Detalle Escena Pelicula</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCoreLinqToXML/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCoreLinqToXML</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCoreLinqToXML.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCoreLinqToXML</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Joyerias" asp-action="Index">Joyerias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Peliculas" asp-action="Index">Peliculas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCoreLinqToXML - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>